# Elasticsearch version from debian repository
es_version: 1.5
# Address of elasticsearch used by fluentd
es_fqdn: localhost
es_port: 9200
# Curator tool
install_curator: False
curator_max_keep_days: 90
# Head plugin
install_head: False
# ElasticHQ plugin
install_eshq: False
# Marvel plugin
install_marvel: False
