---

- name: compiling and installing elasticsearch plugin dependencies
  command: /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-elasticsearch

- name: restart fluentd
  service: name=td-agent state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted
